//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Application
{
    using System;
    using System.Collections.Generic;
    
    public partial class buzz
    {
        public int id { get; set; }
        public Nullable<int> buzzerid { get; set; }
        public Nullable<int> buzzeeid { get; set; }
        public System.DateTime timestamp { get; set; }
    
        public virtual hivemember hivemember { get; set; }
        public virtual hivemember hivemember1 { get; set; }
    }
}
