//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Application
{
    using System;
    
    public partial class GetPotentialMatch_Result1
    {
        public int id { get; set; }
        public string firstname { get; set; }
        public string lastname { get; set; }
        public string nick { get; set; }
        public System.DateTime birthdate { get; set; }
        public string jobtitle { get; set; }
        public string bio { get; set; }
        public Nullable<int> weight { get; set; }
    }
}
