//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Application
{
    using System;
    using System.Collections.Generic;
    
    public partial class message
    {
        public int id { get; set; }
        public Nullable<int> senderid { get; set; }
        public Nullable<int> recieverid { get; set; }
        public System.DateTime timestamp { get; set; }
        public string text { get; set; }
        public bool isread { get; set; }
    
        public virtual hivemember hivemember { get; set; }
        public virtual hivemember hivemember1 { get; set; }
    }
}
