//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Application
{
    using System;
    using System.Collections.Generic;
    
    public partial class preference
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public preference()
        {
            this.hivemembers = new HashSet<hivemember>();
        }
    
        public int id { get; set; }
        public Nullable<int> haircolorid { get; set; }
        public Nullable<int> eyecolorid { get; set; }
        public Nullable<int> heightmin { get; set; }
        public Nullable<int> heightmax { get; set; }
        public Nullable<int> weightmin { get; set; }
        public Nullable<int> weightmax { get; set; }
        public bool attractionmale { get; set; }
        public bool attractionfemale { get; set; }
    
        public virtual eyecolor eyecolor { get; set; }
        public virtual haircolor haircolor { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<hivemember> hivemembers { get; set; }
    }
}
